<?php
$this->ckEditor();
$this->htmlElement('body')->appendAttribute('class', 'timelines add');
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/timeline-item-pool.js', 'Timeline'));
$form->prepare();
$sectionNavs = [
    'admin' => $this->translate('Parameters'),
    'item-pool' => $this->translate('Item Pool')
];
?>
<?php echo $this->pageTitle('Add Timeline'); ?>
<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <a href="#" class="o-icon-private button" aria-label=" <?php echo $this->translate('Make public'); ?>" title=" <?php echo $this->translate('Make public'); ?>"></a>
    <input type="hidden" name="o-module-timeline:is_public" value="0">
    <button><?php echo $this->translate('Add'); ?></button>
</div>

<?php echo $this->sectionNav($sectionNavs); ?>
<fieldset id="admin" class="section active" aria-labelledby="admin-label">
    <?php echo $this->formCollection($form, false); ?>
</fieldset>

<fieldset id="item-pool" class="section" aria-labelledby="item-pool-label">
    <p><em><?php echo $this->translate('Items without a date are automatically filtered.'); ?></em></p>
    <div id="advanced-search"><?php echo $this->partial('common/advanced-search', ['resourceType' => 'item']); ?></div>
</fieldset>
<?php echo $this->form()->closeTag(); ?>
