<?php
$this->htmlElement('body')->appendAttribute('class', 'timelines browse');
$escape = $this->plugin('escapeHtml');
$sortHeadings = [
    [
        'label' => $this->translate('Title'),
        'value' => 'title',
    ],
    [
        'label' => $this->translate('URL slug'),
        'value' => 'slug',
    ],
    [
        'label' => $this->translate('Owner'),
        'value' => 'owner_name',
    ],
    [
        'label' => $this->translate('Date Created'),
        'value' => 'created',
    ],
    [
        'label' => $this->translate('Date Modified'),
        'value' => 'modified',
    ],
];
?>

<?php echo $this->pageTitle($this->translate('Timelines')); ?>

<?php echo $this->searchFilters(); ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Timeline\Api\Adapter\TimelineAdapter', 'create')): ?>
    <?php echo $this->hyperlink($this->translate('Add new timeline'), $this->url('admin/add-timeline', [], true), ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<?php if (empty($timelines)): ?>
<div class="no-resources">
    <p><?php echo $this->translate('There are no timelines.'); ?></p>
</div>

<?php else: ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Date Created'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($timelines as $timeline): ?>
        <?php
        if ($owner = $timeline->owner()) {
            $ownerText = $this->hyperlink(
                $owner->name(),
                $this->url('admin/id', [
                    'controller' => 'user',
                    'action' => 'show',
                    'id' => $owner->id()]
                )
            );
        } else {
            $ownerText = $this->translate('[no owner]');
        }
        ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $timeline->link($timeline->title()); ?>
                </span>
                <ul class="actions">
                    <?php if ($timeline->userIsAllowed('update')): ?>
                    <li><?php echo $timeline->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'aria-label' => $this->translate('Edit'),
                        'title' => $this->translate('Edit'),
                    ]); ?></li>
                    <?php endif; ?>
                    <?php if ($timeline->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($timeline->url('delete-confirm')); ?>"
                        class="o-icon-delete sidebar-content"
                        aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                        title="<?php echo $escape($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($timeline->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escape($this->translate('Details')); ?>"
                        title="<?php echo $escape($this->translate('Details')); ?>"></a></li>
                </ul>
            </td>
            <td><?php echo $ownerText; ?></td>
            <td><?php echo $escape($this->i18n()->dateFormat($timeline->created())); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div class="sidebar-content"></div>
</div>

<?php endif; ?>
