<?php
/**
 * The show view for the Timelines administrative panel.
 */

$timelineTitle = metadata($timeline, 'title');
$head = array(
    'bodyclass' => 'timelines primary',
    'title' => __('Timelines | %s', strip_formatting($timelineTitle)),
);
echo head($head);
echo flash();
?>

<div id="primary" class="seven columns alpha">

    <!-- Construct the timeline. -->
    <?php
    $library = get_option('timeline_library') ?: 'simile';
    $libraryPartial = $library == 'simile' ? '_timeline' : '_timeline_' . $library;
    echo $this->partial('timelines/' . $libraryPartial . '.php',
        array(
            'timeline' => $timeline,
    )); ?>

<?php
$query = $timeline->getQuery();
if ($query) {
?>
    <h2><?php echo __('Items Query'); ?></h2>
    <p><strong><?php echo __('The &#8220;%s&#8221; timeline displays items that match the following query:', $timelineTitle); ?></strong></p>
    <?php
echo item_search_filters($query);
} ?>

</div>

<div class="three columns omega">
    <div id="edit" class="panel">
    <?php if (is_allowed($timeline, 'edit')): ?>
        <?php echo link_to($timeline, 'edit', __('Edit Metadata'), array('class' => 'big green button')); ?>
        <?php echo link_to($timeline, 'query', __('Edit Items Query'), array('class' => 'big green button')); ?>
    <?php endif; ?>
    <a href="<?php echo html_escape(public_url('timeline/timelines/show/'.timeline('id'))); ?>" class="big blue button"><?php echo __('View Public Page'); ?></a>
    <?php echo link_to($timeline, 'delete-confirm', __('Delete'), array('class' => 'delete-confirm big red button')); ?>
    </div>
</div>
<script>
var jsonTimelineUri = '<?php echo timeline_json_uri_for_timeline(); ?>';
$.getJSON(jsonTimelineUri, function(data) {
    if (data.events.length > 100) {
        alert(<?php echo json_encode(__('Adding more than 100 items to the timeline will create slow render times.')); ?>);
    }
});
</script>
<?php echo foot();
