<?php $escape = $this->plugin('escapeHtml'); ?>
<div class="resource-details" data-resource-values="<?php //echo $escape($values); ?>">
    <h3 class="o-title"><?php echo $resource->link($resource->title()); ?></h3>
    <div class="o-description"><?php echo $resource->description(); ?></div>
    <div class="meta-group">
        <h4><?php echo $escape($this->translate('Visibility')); ?></h4>
        <div class="value"><?php echo ($resource->isPublic()) ? $this->translate('Public') : $this->translate('Private'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Date Created'); ?></h4>
        <div class="value"><?php echo $escape($this->i18n()->dateFormat($resource->created())); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Date Modified'); ?></h4>
        <div class="value"><?php echo $escape($this->i18n()->dateFormat($resource->modified())); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Items in Pool'); ?></h4>
        <div class="value"><?php echo $this->hyperlink($resource->itemCount(), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['timeline_slug' => $resource->slug()]])); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Internal Id'); ?></h4>
        <div class="value"><?php echo $resource->id(); ?></div>
    </div>
</div>
