<?php
$this->htmlElement('body')->appendAttribute('class', 'timelines show');
$escape = $this->plugin('escapeHtml');

$library = $this->setting('timeline_library');

switch ($library):
case 'knightlab':
    $this->headLink()->appendStylesheet('//cdn.knightlab.com/libs/timeline3/latest/css/timeline.css');
    $this->headScript()->appendFile('//cdn.knightlab.com/libs/timeline3/latest/js/timeline.js');
    break;
case 'simile':
default:
    $this->headLink()->appendStylesheet($this->assetUrl('css/timeline.css', 'Timeline'));
    $this->headScript()->appendFile($this->assetUrl('js/timeline.js', 'Timeline'));
    if ($external) {
        $this->headScript()->appendFile('//api.simile-widgets.org/timeline/2.3.1/timeline-api.js?bundle=true');
        $this->headScript()->appendScript('SimileAjax.History.enabled = false; window.jQuery = SimileAjax.jQuery;');
    } else {
    $timelineVariables = 'Timeline_ajax_url="' . $this->assetUrl('js/simile/ajax-api/simile-ajax-api.js', 'Timeline') . '";
            Timeline_urlPrefix="' . dirname($this->assetUrl('js/simile/timeline-api/timeline-api.js', 'Timeline')) . '/";
            Timeline_parameters="bundle=true";';
        $this->headScript()->appendScript($timelineVariables);
        $this->headScript()->appendFile($this->assetUrl('js/simile/timeline-api/timeline-api.js', 'Timeline'));
        $this->headScript()->appendScript('SimileAjax.History.enabled = false; // window.jQuery = SimileAjax.jQuery;');
    }
    break;
endswitch;

if ($owner = $timeline->owner()) {
    $ownerText = $this->hyperlink(
        $owner->name(),
        $this->url('admin/id', [
            'controller' => 'user',
            'action' => 'show',
            'id' => $owner->id()]
        )
    );
} else {
    $ownerText = $this->translate('[no owner]');
}
?>

<?php echo $this->pageTitle(sprintf($this->translate('Timeline: “%s”'), $timeline->title())); ?>

<div id="page-actions">
    <?php if ($timeline->userIsAllowed('delete')): ?>
    <a href="#" class="delete button"><?php echo $this->translate('Delete'); ?></a>
    <?php endif; ?>
    <?php if ($timeline->userIsAllowed('update')): ?>
        <?php echo $timeline->link($this->translate('Edit'), 'edit', ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<div class="active section">
<?php
    echo $this->partial(
        'timeline/site/timeline/_timeline_' . $library,
        ['timeline' => $timeline]
    );
    ?>
    <div class="meta-group">
        <div><?php echo $timeline->description(); ?></div>
    </div>
</div>

<div class="sidebar active">
    <div class="meta-group">
        <h4><?php echo $this->translate('Visibility'); ?></h4>
        <div class="value"><?php echo ($timeline->isPublic()) ? $this->translate('Public') : $this->translate('Private'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Owner'); ?></h4>
        <div class="value"><?php echo $ownerText; ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Date Created'); ?></h4>
        <div class="value"><?php echo $escape($this->i18n()->dateFormat($timeline->created())); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Date Modified'); ?></h4>
        <div class="value"><?php echo $escape($this->i18n()->dateFormat($timeline->modified())); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Items in Pool'); ?></h4>
        <div class="value"><?php echo $this->hyperlink($timeline->itemCount(), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['timeline_slug' => $timeline->slug()]])); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Parameters'); ?></h4>
        <?php
            $timelineArgs = $timeline->args();
            unset($timelineArgs['viewer']);
            unset($timelineArgs['item_date_id']);
            foreach ($timelineArgs as $argKey => $argValue):
                $argName = ucfirst(str_replace('_', ' ', $argKey));
        ?>
        <div class="value">
            <em><strong><?php echo $this->translate($argName); ?>:&nbsp;</em></strong><?php echo $argValue; ?></div>
        <?php endforeach; ?>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Internal Id'); ?></h4>
        <div class="value"><?php echo $timeline->id(); ?></div>
    </div>
</div>
<?php echo $this->deleteConfirm($timeline, 'timeline'); ?>
