<?php $args = $timeline->args(); ?>
<div id="<?php echo $timeline->slug(); ?>" class="timeline"></div>
<script>
    jQuery(document).ready(function($) {
        var params = <?php echo $args['viewer']; ?>;
        if (typeof params.centerDate === 'undefined') {
            params.centerDate = <?php echo json_encode($args['center_date']); ?>;
        }

        oTimeline.loadTimeline(
            '<?php echo $timeline->slug(); ?>',
            '<?php echo $this->url('timeline-events', ['timeline-slug' => $timeline->slug()]); ?>',
            params
        );
    });
</script>
