<?php
$library = $this->setting('timeline_library');
switch ($library):
case 'knightlab':
    $this->headLink()->appendStylesheet('//cdn.knightlab.com/libs/timeline3/latest/css/timeline.css');
    $this->headScript()->appendFile('//cdn.knightlab.com/libs/timeline3/latest/js/timeline.js');
    break;

case 'simile':
default:
   $this->headLink()->appendStylesheet($this->assetUrl('css/timeline.css', 'Timeline'));
    $this->headScript()->appendFile($this->assetUrl('js/timeline.js', 'Timeline'));
    if (!empty($external)) {
        $this->headScript()->appendFile('//api.simile-widgets.org/timeline/2.3.1/timeline-api.js?bundle=true');
        $this->headScript()->appendScript('SimileAjax.History.enabled = false; window.jQuery = SimileAjax.jQuery;');
    } else {
        $timelineVariables = 'Timeline_ajax_url="' . $this->assetUrl('js/simile/ajax-api/simile-ajax-api.js', 'Timeline') . '";
            Timeline_urlPrefix="' . dirname($this->assetUrl('js/simile/timeline-api/timeline-api.js', 'Timeline')) . '/";
            Timeline_parameters="bundle=true";';
        $this->headScript()->appendScript($timelineVariables);
        $this->headScript()->appendFile($this->assetUrl('js/simile/timeline-api/timeline-api.js', 'Timeline'));
        $this->headScript()->appendScript('SimileAjax.History.enabled = false; // window.jQuery = SimileAjax.jQuery;');
    }
    break;
endswitch;
