<?php
/**
 * Timeline display partial.
 */

// Get the timeline
if (empty($timeline)) $timeline = get_current_record('timeline');
?>

<!-- Container. -->
<div id="<?php echo timeline_id(); ?>" class="timeline-timeline">
</div>
<script>
    jQuery(document).ready(function($) {
        var params = <?php echo $timeline->getViewerParameters(); ?>;
        if (typeof params.centerDate === 'undefined') {
            params.centerDate = <?php echo json_encode($timeline->getProperty('center_date')); ?>;
        }

        oTimeline.loadTimeline(
            '<?php echo timeline_id($timeline); ?>',
            '<?php echo timeline_json_uri_for_timeline($timeline); ?>',
            params
        );
    });
</script>
