<?php $escape = $this->plugin('escapeHtml');?>
<?php $this->htmlElement('body')->appendAttribute('class', 'timeline resource browse'); ?>

<?php echo $this->pageTitle($this->translate('Timelines'), 2); ?>

<?php if (empty($timelines)): ?>
<div class="no-resources">
    <p><?php echo $this->translate('There are no timelines.'); ?></p>
</div>
<?php else: ?>
<?php echo $this->pagination(); ?>
<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
    <?php foreach ($timelines as $timeline): ?>
    <li class="timeline resource">
        <?php if ($primaryMedia = $timeline->primaryMedia()): ?>
        <img
            src="<?php echo $escape($primaryMedia->thumbnailUrl('medium')); ?>"
            title="<?php echo $escape($primaryMedia->displayTitle()); ?>"
            alt="<?php echo $escape($primaryMedia->mediaType()); ?> thumbnail"
        >
        <?php endif; ?>
        <h4><?php echo $timeline->link($timeline->title()); ?></h4>
        <?php if ($description = $timeline->description()): ?>
        <div class="description"><?php
        $description= strip_tags($description);
        echo strlen($description) <= 200 ? $description: substr($description, 0, 199) . '&hellip;';
        ?></div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
<?php endif; ?>
