<?php
/**
 * The public show view for Timelines.
 */

$timelineTitle = metadata($timeline, 'title');
$head = array(
    'bodyclass' => 'timelines primary',
    'title' => $timelineTitle,
);
echo head($head);
?>
<h1><?php echo $timelineTitle; ?></h1>
    <?php // Construct the timeline.
    $library = get_option('timeline_library') ?: 'simile';
    $libraryPartial = $library == 'simile' ? '_timeline' : '_timeline_' . $library;
    echo $this->partial('timelines/' . $libraryPartial . '.php',
        array(
            'timeline' => $timeline,
    )); ?>
    <?php echo metadata($timeline, 'description'); ?>
<?php echo foot();
