<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'timeline resource show');
$library = $this->setting('timeline_library');
echo $this->partial('common/timeline_header', ['external' => $external]);
?>

<?php echo $this->pageTitle($timeline->title(), 2); ?>
<h3><?php echo $this->translate('Timeline'); ?></h3>
<?php $this->trigger('view.show.before'); ?>
<div class="timeline-render">
<?php echo $this->partial('common/timeline_' . $library, ['timeline' => $timeline]); ?>
</div>
<?php echo $timeline->description(); ?>
<?php $this->trigger('view.show.after'); ?>
