<?php
$library = get_option('timeline_library');
if ($library == 'knightlab') {
    queue_css_url('//cdn.knightlab.com/libs/timeline3/latest/css/timeline.css');
    queue_js_url('//cdn.knightlab.com/libs/timeline3/latest/js/timeline.js');
    return;
}

// Default simile library.
queue_css_file('timeline-timeline');

queue_js_file('timeline-scripts');

// Check useInternalJavascripts in config.ini.
$config = Zend_Registry::get('bootstrap')->getResource('Config');
$useInternalJs = isset($config->theme->useInternalJavascripts)
    ? (bool) $config->theme->useInternalJavascripts
    : false;
$useInternalJs = isset($config->theme->useInternalAssets)
    ? (bool) $config->theme->useInternalAssets
    : $useInternalJs;

if ($useInternalJs) {
    $timelineVariables = 'Timeline_ajax_url="' . src('simile-ajax-api.js', 'javascripts/simile/ajax-api') . '";
        Timeline_urlPrefix="' . dirname(src('timeline-api.js', 'javascripts/simile/timeline-api')) . '/";
        Timeline_parameters="bundle=true";';
    queue_js_string($timelineVariables);
    queue_js_file('timeline-api', 'javascripts/simile/timeline-api');
    queue_js_string('SimileAjax.History.enabled = false; // window.jQuery = SimileAjax.jQuery;');
} else {
    queue_js_url('//api.simile-widgets.org/timeline/2.3.1/timeline-api.js?bundle=true');
    queue_js_string('SimileAjax.History.enabled = false; window.jQuery = SimileAjax.jQuery;');
}
