<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $heading
 * @var string $options
 */

$escape = $this->plugin('escapeHtml');

$url = json_encode($this->url('timeline-block', ['block-id' => $block->id()]), 320);
$blockId = $block->id();
$options = json_decode($options) ? $options : json_encode(['start_at_slide' => 1, 'language' => substr($this->siteSetting('locale'), 0, 2)]);

$js = <<<JS
jQuery(document).ready(function($) {
    var timelineId = 'timeline-$blockId';
    var timelineUrl = $url;
    var timelineOptions = $options;
    $.getJSON(timelineUrl, function(data) {
        window.timeline = new TL.Timeline(timelineId, data, timelineOptions);
    });
});
JS;
$this->headScript()->appendScript($js);
?>

<?php if (!empty($heading)): ?>
<h2><?= $escape($heading) ?></h2>
<?php endif; ?>

<div id="timeline-<?= $blockId ?>" class="timeline" style="width: 100%; height: 80vh"></div>
