<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var array $data
 */

$escape = $this->plugin('escapeHtml');
?>

<?php if (!empty($data['heading'])): ?>
<h2><?= $escape($data['heading']) ?></h2>
<?php endif; ?>

<div id="timeline-<?= $block->id() ?>" class="timeline"></div>
<script>
    jQuery(document).ready(function($) {
        var params = <?= $data['viewer'] ?>;
        if (typeof params.centerDate === 'undefined') {
            params.centerDate = <?= json_encode($data['center_date']) ?>;
        }

        oTimeline.loadTimeline(
            'timeline-<?= $block->id() ?>',
            <?= json_encode($this->url('api/timeline', ['block-id' => $block->id()]), 320) ?>,
            params
        );
    });
</script>
