<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var array $data
 */

// TODO Move the script in a external js but manage multiple timelines.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');

$this->headLink()
    ->appendStylesheet($assetUrl('css/timeline.css', 'Timeline'));
$this->headScript()
    ->appendFile($assetUrl('js/timeline.js', 'Timeline'))
    ->appendFile('https://simile-widgets.org/timeline/api/timeline-api.js?bundle=true')
    ->appendScript('SimileAjax.History.enabled = false; window.jQuery = SimileAjax.jQuery;');
?>

<div id="timeline-<?= $block->id() ?>" class="timeline"></div>

<script>
    jQuery(document).ready(function($) {
        var params = <?= $data['viewer'] ?>;
        if (typeof params.centerDate === 'undefined') {
            params.centerDate = <?= json_encode($data['center_date']) ?>;
        }

        oTimeline.loadTimeline(
            'timeline-<?= $block->id() ?>',
            <?= json_encode($this->url('api/timeline', ['block-id' => $block->id()]), 320) ?>,
            params
        );
    });
</script>
